# Generated by Django 4.2 on 2023-04-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postrating'),
        ),
    ]
