# Generated by Django 4.2 on 2023-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.CharField(max_length=4)),
                ('car_color', models.CharField(max_length=30)),
            ],
        ),
    ]
