# Generated by Django 4.2 on 2023-04-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_serviceplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='service_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_app.serviceplan'),
        ),
    ]
